insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (71, 77, 'alliance', '2/23/2023', 13);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (44, 35, 'Multi-layered', '4/11/2023', 3);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (96, 67, 'static', '8/17/2023', 58);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (41, 69, 'Seamless', '3/12/2023', 93);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (18, 18, 'open system', '1/14/2023', 57);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (28, 79, 'Cross-platform', '4/22/2023', 55);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (68, 70, 'Pre-emptive', '1/26/2023', 35);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (37, 4, 'model', '8/12/2023', 98);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (7, 12, 'impactful', '6/19/2023', 63);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (64, 50, 'functionalities', '1/26/2023', 64);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (84, 93, '6th generation', '11/13/2023', 79);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (62, 97, 'orchestration', '9/12/2023', 20);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (59, 48, 'Assimilated', '3/30/2023', 78);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (46, 29, 'Stand-alone', '1/24/2023', 96);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (43, 89, '3rd generation', '6/27/2023', 68);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (85, 37, 'Persistent', '7/30/2023', 46);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (38, 58, 'Configurable', '8/2/2023', 29);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (60, 5, 'strategy', '12/4/2023', 67);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (93, 53, 'Assimilated', '5/24/2023', 14);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (13, 27, 'emulation', '9/27/2023', 92);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (41, 43, 'discrete', '11/23/2023', 60);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (55, 32, 'local area network', '2/23/2023', 69);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (66, 68, 'portal', '6/9/2023', 20);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (60, 17, 'Implemented', '6/7/2023', 3);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (65, 66, 'Business-focused', '11/29/2023', 38);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (59, 71, 'Universal', '1/12/2023', 78);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (65, 11, 'Compatible', '7/23/2023', 49);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (52, 86, 'impactful', '1/13/2023', 1);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (12, 79, 'background', '9/2/2023', 85);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (55, 41, 'coherent', '1/3/2023', 82);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (59, 3, 'Vision-oriented', '9/30/2023', 39);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (85, 27, 'asymmetric', '8/14/2023', 10);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (14, 42, 'Mandatory', '5/11/2023', 31);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (76, 21, 'Cross-platform', '3/8/2023', 39);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (43, 39, 'dynamic', '4/9/2023', 71);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (41, 80, 'encryption', '8/13/2023', 53);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (6, 89, 'Multi-layered', '3/1/2023', 59);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (71, 91, 'implementation', '11/17/2023', 3);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (93, 26, 'process improvement', '7/27/2023', 84);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (99, 55, 'homogeneous', '6/3/2023', 69);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (92, 69, 'clear-thinking', '2/20/2023', 21);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (37, 15, 'emulation', '3/16/2023', 35);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (81, 82, 'Reverse-engineered', '7/13/2023', 16);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (39, 97, 'Cross-platform', '7/9/2023', 45);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (87, 27, 'superstructure', '11/29/2023', 10);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (78, 62, 'multi-tasking', '12/7/2023', 58);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (72, 32, 'analyzing', '12/19/2022', 59);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (86, 23, '5th generation', '12/23/2022', 65);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (77, 93, 'core', '2/8/2023', 53);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (38, 39, 'national', '12/2/2023', 49);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (6, 18, 'Down-sized', '3/6/2023', 8);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (62, 95, 'definition', '11/23/2023', 40);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (26, 59, 'internet solution', '12/13/2022', 41);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (83, 83, 'Reduced', '9/6/2023', 56);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (58, 97, 'Multi-lateral', '6/17/2023', 78);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (59, 91, 'Inverse', '3/5/2023', 58);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (31, 63, 'conglomeration', '1/17/2023', 43);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (45, 60, 'De-engineered', '12/11/2022', 4);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (26, 39, 'implementation', '3/14/2023', 11);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (50, 3, 'zero defect', '1/25/2023', 40);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (95, 67, 'task-force', '8/5/2023', 42);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (31, 38, 'superstructure', '1/6/2023', 38);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (35, 58, '5th generation', '11/1/2023', 57);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (74, 23, 'zero administration', '7/12/2023', 12);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (77, 66, 'discrete', '2/23/2023', 47);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (34, 88, 'Pre-emptive', '1/3/2023', 63);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (7, 76, 'Universal', '11/21/2023', 51);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (96, 2, 'functionalities', '12/10/2022', 87);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (54, 43, 'complexity', '3/4/2023', 75);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (87, 96, 'standardization', '6/21/2023', 31);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (77, 89, 'transitional', '12/19/2022', 54);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (39, 73, 'project', '6/21/2023', 16);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (29, 14, 'Devolved', '3/29/2023', 92);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (28, 91, 'multi-tasking', '1/15/2023', 47);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (3, 17, 'methodology', '12/7/2023', 93);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (62, 46, 'benchmark', '3/1/2023', 12);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (49, 3, 'project', '6/5/2023', 9);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (44, 77, 'capacity', '8/3/2023', 55);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (21, 9, 'asynchronous', '11/1/2023', 39);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (6, 49, 'holistic', '6/16/2023', 72);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (37, 48, 'bifurcated', '9/26/2023', 4);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (98, 67, 'Devolved', '3/29/2023', 42);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (2, 70, 'hardware', '10/20/2023', 81);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (3, 37, 'mobile', '12/15/2022', 22);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (73, 54, 'Right-sized', '9/18/2023', 69);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (56, 85, 'task-force', '6/12/2023', 87);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (86, 1, 'hierarchy', '11/11/2023', 41);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (6, 84, 'Extended', '11/19/2023', 9);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (41, 73, 'Advanced', '4/26/2023', 23);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (39, 45, 'Up-sized', '7/8/2023', 50);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (91, 77, 'Secured', '9/10/2023', 13);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (32, 79, 'global', '5/1/2023', 44);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (84, 97, 'Synergized', '11/23/2023', 67);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (51, 95, 'hub', '4/8/2023', 17);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (3, 84, 'Object-based', '1/31/2023', 9);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (82, 39, 'infrastructure', '12/18/2022', 75);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (83, 12, 'Persistent', '7/12/2023', 49);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (18, 60, 'attitude', '1/23/2023', 86);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (10, 31, 'productivity', '6/29/2023', 66);
insert into contest_grading (user_id, problem_id, answer, submitted_at, score) values (44, 1, 'explicit', '6/12/2023', 17);