services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  frontend:
    build: 
      context: ./frontend
    ports:
      - 80:80
