import secrets
import hashlib
import base64

code_verifier = tmp if not (tmp := input("Enter code verifier (leave empty for autogenerated): ")) == "" else secrets.token_urlsafe(64)

code_challenge = base64.urlsafe_b64encode(hashlib.sha256(code_verifier.encode()).digest()).decode().replace("=", "")

print(f"Code verifier: {code_verifier}")
print(f"Code challenge: {code_challenge}")